server:
  port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # MYSQL5驱动：com.mysql.jdbc.Driver，MYSQL5.8+ 驱动：com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mark?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    #连接池配置
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM sys_user
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙
      # filters: stat,wall,log4j
      # 通过 connection-properties 属性打开 mergeSql 功能；慢 SQL 记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置 DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: .js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*
      # 配置 DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        # IP 白名单，没有配置或者为空，则允许所有访问
        allow: 127.0.0.1
        # IP 黑名单，若白名单也存在，则优先使用
        deny: 192.168.31.253
        # 禁用 HTML 中 Reset All 按钮
        reset-enable: false
        # 登录用户名/密码
        login-username: root
        login-password: 123

  #    username: root
  #    password: 123456
  #    url: jdbc:mysql://127.0.0.1:3306/mark?useUnicode=true&useSSL=false&characterEncoding=utf-8
  #    driver-class-name: com.mysql.jdbc.Driver
  #    max-idle: 10
  #    max-wait: 10000
  #    min-idle: 5
  #    initial-size: 5

  #时间配置对Date格式起作用
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
    host: 172.16.188.11
    port: 8679
    password: 123456
    database: 0
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000
# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: top.suiyueran.user.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      # 主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: auto
      # 字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_NULL
      # 数据库类型
      db-type: MYSQL
      # 逻辑删除配置（逻辑删除字段不能更新）
      logic-delete-value: 0
      logic-not-delete-value: 1
      #配置表前缀：如果实体名与表名不一致，配置前缀没有，需要在实体上配置实际表名，使用@TableName注解
      table-prefix: mark_
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



jwt:
  secret: 123153445hnmfjhfhjfmbjkjhfvhjvhjv
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600